### ISSUE TITLE
The app crashed after I tried to view the favorite's page after adding an author as favorite.

### ISSUE THREAD

**Issue by HarryHeights** [hispeedimagins/steem#26]
The app crashed after I added an author as favourite and tried to view the page. 

Here is a logcat of the crash

```kotlin.KotlinNullPointerException
	at com.steemapp.lokisveil.steemapp.BindHelpers.FeedHelperFunctions.Bind(FeedHelperFunctions.kt:130)
	at com.steemapp.lokisveil.steemapp.AllRecyclerViewAdapter.onBindViewHolder(AllRecyclerViewAdapted.kt:340)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
	at android.view.View.layout(View.java:19685)
	at android.view.ViewGroup.layout(ViewGroup.java:6077)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2538)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2254)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1434)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6868)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
	at android.view.Choreographer.doCallbacks(Choreographer.java:838)
	at android.view.Choreographer.doFrame(Choreographer.java:769)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:171)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
``` 

## Test enviroment: 
Device: Redmi Note 5 pro
OS: Android 8.1

## Video recording. 
https://www.youtube.com/watch?v=24qwVvzLB98

**Comment by hispeedimagins** [comment]
thank you, will look into it.

**Comment by hispeedimagins** [comment]
fixed
