### ISSUE TITLE
The app crashed after nonce was set to 1 trillion. 

### ISSUE THREAD

**Issue by HarryHeights** [hispeedimagins/steem#28]
I don't really know how the nonce stuff works. However you stated that it has something to do with performing operations on the app. 
What you didn't say is, if a higher nonce or lower nonce is better. 

I tried a very high nonce 1 trillion to be exact and the app crashed.

Maybe I'm not supposed to get to that limit, but since there's no maximum limit set on the app, I expected that churning up the nonce to that level wouldn't hurt.

## Logcat of the crash

```java.lang.NumberFormatException: For input string: "1000000000000"
	at java.lang.Integer.parseInt(Integer.java:611)
	at java.lang.Integer.parseInt(Integer.java:643)
	at com.steemapp.lokisveil.steemapp.HelperClasses.GetDynamicAndBlock.<init>(GetDynamicAndBlock.kt:78)
	at com.steemapp.lokisveil.steemapp.HelperClasses.GetDynamicAndBlock.<init>(GetDynamicAndBlock.kt:63)
	at com.steemapp.lokisveil.steemapp.HelperClasses.VoteWeightThenVote$makeDialog$3.onClick(VoteWeightThenVote.kt:184)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:171)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

## Video recording
https://youtu.be/VQPNZC4Tnbg

**Comment by hispeedimagins** [comment]
thank you, was not meant for that, I'll add a limit on it.

**Comment by hispeedimagins** [comment]
fixed
