### ISSUE TITLE
The app crashed when I scrolled on the upvotes/comments page. 

### ISSUE THREAD

**Issue by HarryHeights** [hispeedimagins/steem#33]
#### Expected Behavior
I expected that I could scroll on the comments/replies page for as long as I wished. 

#### Actual Behaviour
The app crashed while scrolling through the content of the page. 

#### Steps to reproduce
After doing all the necessary things to get into the app;

- Access the options menu by clicking the 3 horizontal bar at the top left of the app.
- Click on "comments/replies"
- You can decide if you wish to scroll on the comments page or replies page. Any of them will produce same error.
- Scroll on the comments/replies page. 
- Scroll until the error occurs. 

#### Test Environment

Device: Redmi Note 5 Pro
OS: Android 8.1
Software version:  Insteem v1.5.0

#### Screen recording

https://youtu.be/iWooNihddPA

#### Logcat

``` java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	... 1 more
Caused by: org.json.JSONException: Value {"error":{"code":-32000,"message":"get_discussions_by_comments() got an unexpected keyword argument 'tag' (hivemind-alpha)"}} at result of type org.json.JSONObject cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:100)
	at org.json.JSONObject.getJSONArray(JSONObject.java:591)
	at com.insteem.ipfreely.steem.HelperClasses.JsonRpcResultConversion.ParseJsonBlogMore(JsonRpcResultConversion.kt:228)
	at com.insteem.ipfreely.steem.HelperClasses.JsonRpcResultConversion.ParseJsonBlogMore$default(JsonRpcResultConversion.kt:219)
	at com.insteem.ipfreely.steem.CommentNotificationsSteemitFragment.addMoreItems(CommentNotificationsSteemitFragment.kt:375)
	at com.insteem.ipfreely.steem.CommentNotificationsSteemitFragment$GetMoreItems$s$1.onResponse(CommentNotificationsSteemitFragment.kt:354)
	at com.insteem.ipfreely.steem.CommentNotificationsSteemitFragment$GetMoreItems$s$1.onResponse(CommentNotificationsSteemitFragment.kt:37)
	at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	... 3 more
```

**Comment by hispeedimagins** [comment]
fixed

**Comment by HarryHeights** [comment]
Great. When will the new apk release be available?

**Comment by hispeedimagins** [comment]
I think I pushed it don't remember, just check if there is an update

**Comment by HarryHeights** [comment]
Seen it. Testing it for new bugs 😁😁
